#!/usr/bin/python2

# gen .h file from reference
# TODO : PIL graphical with tables + colors + signification. one file per table.

import sys

def camel(s) : 
	return ''.join(x.capitalize() for x in s.split())

def parse(file) : 
	section=None
	table=[]
	header=None
	comments=[]

	for l in file : 
		l=l.strip()
		if not l : continue

		if l.startswith('### ') : 
			# preceding section : send
			if table : yield section, header, table, comments
			section=l[3:].strip()
			table=[]
			header=None
			comments=[]
		elif len(l.split('|')) != 3 : 
			comments.append(l) 
		elif section : 
			if not header : 
				header = l.split('|')
			elif l.startswith('---') : 
				continue
			else :
				table.append(x.strip() for x in l.split('|'))
		
	yield section, header, table, comments

if __name__=='__main__' : 
	print '#pragma once'
	print '// Enums for game generated by %s from %s \n\n'%tuple(sys.argv)

	for section, header, table, comments in parse(open(sys.argv[1])) : 
		print '/* '
		print ' * %s'%section
		print ' * %s'%('='*len(section))	
		for l in comments : 
			print ' * %s'%l
		print ' */\n'
		print 'enum %s {'%camel(section)
		for name,id,comment in table : 
			n = header[0].lower().strip()+'_'+name
			if id : 
				print '    %s=%s, // %s'%(n,id,comment)
			else : 
				print '    // TODO : %s - %s'%(n,comment)
		print '};\n'
